### ISSUE TITLE
New pypi release

### ISSUE THREAD

**Issue by iloveitaly** [anntzer/ipython-autoimport#11]
Hello, the current PyPi release causes an exception with the latest IPython version. It would be great to get the master version released publicly.

It's always a pain when people ask for updates without offering to help. I'm happy to set up an automatic script for this or help with maintenance on this repo if that would be helpful.

**Comment by anntzer** [comment]
Done!  Thanks for the reminder.

**Comment by iloveitaly** [comment]
Thank you!
